kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: h44/+xNjysi1+YuhQtjOVACoD2mf/j3rvOCPow/d4y8=
      - identity: {}
